---
name: Lint

"on": [push, workflow_dispatch]

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac  # v4.0.0

      # uses .markdownlint.yml for configuration
      - name: markdownlint
        # yamllint disable-line rule:line-length
        uses: DavidAnson/markdownlint-cli2-action@3aaa38e446fbd2c288af4291aa0f55d64651050f  # v12.0.0
        with:
          globs: |
            .github/**/*.md
            *.md
            LICENSE

      - name: yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c  # v3.1.1
        with:
          file_or_dir: |
            .github/**/*.yml
            .*.yml
          strict: true
          config_file: .yamllint.yml

      - name: shellcheck+shfmt
        uses: luizm/action-sh-checker@76ab0b22e1f194e4a582edc7969df6485c4e9246  # v0.7.0
        with:
          scandir: .github/workflows
        env:
          SHELLCHECK_OPTS: -o all
          SHFMT_OPTS: -i 4

      - name: Check push (shfmt)
        run: |
          git diff --exit-code
