---
name: Nightly

"on":
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  release:
    name: Nightly

    strategy:
      matrix:
        macos-vsn: ["11", "12", "13"]
        otp-vsn: ["master", "maint"]  # The same as is_nightly_otp_for, in release.sh
      fail-fast: true
      max-parallel: 1

    runs-on: macos-${{matrix.macos-vsn}}

    steps:
      - uses: ./github/workflows/common.yml
        with:
          macos-vsn: ${{matrix.macos-vsn}}
          otp-vsn: ${{matrix.otp-vsn}}
