---
name: Nightly

"on":
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  release:
    name: Nightly

    strategy:
      matrix:
        darwin-vsn: ["13", "14"]
        otp-vsn: ["master", "maint"]  # The same as is_nightly_otp_for, in release.sh
      fail-fast: true
      max-parallel: 1

    runs-on: macos-${{matrix.darwin-vsn}}

    steps:
      - name: Get branch
        id: branch
        uses: ./.github/actions/get-branch

      - name: Build and release
        uses: ./.github/actions/build-and-release
        with:
          head_ref: ${{steps.branch.outputs.head_ref}}
          darwin-vsn: ${{matrix.darwin-vsn}}
          otp-vsn: ${{matrix.otp-vsn}}
