---
name: Nightly

"on":
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  branch:
    outputs:
      head_ref: ${{steps.branch.outputs.head_ref}}

    runs-on: ubuntu-24.04

    steps:
      - id: branch
        run: |
          head_ref=${GITHUB_REF}
          echo "head_ref is ${head_ref}"
          [[ -z "${head_ref}" ]] && exit 1
          echo "head_ref=${head_ref}" > "${GITHUB_OUTPUT}"

  release:
    name: Nightly

    needs: [branch]

    strategy:
      matrix:
        darwin64-vsn: [12, 13, 14]
        otp-vsn: [master, maint]  # The same as is_nightly_otp_for, in release.sh
      fail-fast: true
      max-parallel: 1

    runs-on: macos-${{matrix.darwin64-vsn}}

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
        with:
          # We want jobs to always checkout the updated branch
          ref: ${{needs.branch.outputs.head_ref}}

      - name: Configure and build
        timeout-minutes: 60
        id: config_build
        run: |
          ./.github/workflows/release.sh ${{matrix.darwin64-vsn}} ${{matrix.otp-vsn}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191  # v2.0.8
        with:
          body: >
            This is
            Erlang/OTP ${{steps.config_build.outputs.otp_vsn}} compiled for
            Darwin ${{matrix.darwin64-vsn}} (64 bit).
          files: |
            ${{steps.config_build.outputs.tar_gz}}
            ${{steps.config_build.outputs.sha256_txt}}
          tag_name: ${{steps.config_build.outputs.git_tag}}
          target_commitish: ${{steps.config_build.outputs.target_commitish}}
        if: "${{github.ref == 'refs/heads/main' &&
             steps.config_build.outputs.target_commitish != ''}}"

      - name: Notify on failed build
        uses: jayqi/failed-build-issue-action@1a893bbf43ef1c2a8705e2b115cd4f0fe3c5649b  # v1.2.0
        if: failure() && github.ref == 'refs/heads/main'
        id: failed-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
