---
name: Release

"on":
  schedule:
    - cron: 0 */2 * * *
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  release:
    name: Release

    strategy:
      matrix:
        macos-vsn: ["11", "12", "13"]
      fail-fast: true
      max-parallel: 1

    runs-on: macos-${{matrix.macos-vsn}}

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac  # v4.0.0
        with:
          # We want jobs to always checkout the updated branch, since we push to it, below
          ref: ${{github.ref_name}}

      - name: Configure and build
        timeout-minutes: 20
        id: config_build
        run: |
          ./.github/workflows/release.sh ${{matrix.macos-vsn}}

      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844  # v1
        with:
          body: >
            This is
            Erlang/OTP ${{steps.config_build.outputs.otp_vsn}} compiled for
            macOS ${{matrix.macos-vsn}} (64 bit).
          fail_on_unmatched_files: true
          files: |
            ${{steps.config_build.outputs.tar_gz}}
            ${{steps.config_build.outputs.sha256_txt}}
          tag_name: macos64-${{matrix.macos-vsn}}/OTP-${{steps.config_build.outputs.otp_vsn}}
          target_commitish: ${{steps.config_build.outputs.target_commitish}}
        if: ${{github.ref == 'refs/heads/main'}}
