---
name: Release

"on":
  schedule:
    - cron: 0 */2 * * *
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  branch:
    outputs:
      head_ref: ${{steps.branch.outputs.head_ref}}

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7

      - id: branch
        uses: ./.github/actions/get-branch

  release:
    name: Release

    needs: [branch]

    strategy:
      matrix:
        darwin-vsn: ["13", "14", "15"]

        # otp-vsn is picked later
      fail-fast: true
      max-parallel: 1

    runs-on: macos-${{matrix.darwin-vsn}}

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
        with:
          # We want jobs to always checkout the updated branch
          ref: ${{needs.branch.outputs.head_ref}}

      - name: Build and release
        timeout-minutes: 60
        uses: ./.github/actions/build-and-release
        with:
          darwin-vsn: ${{matrix.darwin-vsn}}
          # otp-vsn is picked later
          github-token: ${{secrets.GITHUB_TOKEN}}
