---
name: Release

"on":
  schedule:
    - cron: 0 */2 * * *
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  release:
    name: Release

    strategy:
      matrix:
        darwin-vsn: ["13", "14"]
        # otp-vsn is picked later
      fail-fast: true
      max-parallel: 1

    runs-on: macos-${{matrix.darwin-vsn}}

    steps:
      - name: Get branch
        id: branch
        uses: ./.github/actions/get-branch

      - name: Build and release
        uses: ./.github/actions/build-and-release
        with:
          head_ref: ${{steps.branch.outputs.head_ref}}
          darwin-vsn: ${{matrix.darwin-vsn}}
          # otp-vsn is picked later
