---
name: Release

"on":
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  release:
    name: Release

    strategy:
      matrix:
        macos-vsn: ["11", "12", "13"]
      fail-fast: true
      max-parallel: 1

    runs-on: macos-${{matrix.macos-vsn}}

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac  # v4.0.0
        with:
          # We want jobs to always checkout the updated branch, since we push to it, below
          ref: ${{github.ref_name}}

      - name: Configure and build
        timeout-minutes: 20
        id: configure
        run: |
          ./.github/workflows/release.sh ${{matrix.macos-vsn}}

      - name: Update _RELEASES
        id: update_releases
        run: |
          filename_no_ext="macos64-${{matrix.macos-vsn}}-OTP-${{steps.configure.outputs.otp_vsn}}"
          ./.github/workflows/update__releases.sh "$filename_no_ext"

      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844  # v1
        with:
          body: >
            This is
            Erlang/OTP ${{steps.configure.outputs.otp_vsn}} compiled for
            macOS ${{matrix.macos-vsn}} (64 bit).
          fail_on_unmatched_files: true
          # yamllint disable-line rule:line-length
          files: |
            ${{runner.temp}}/otp/macos64-${{matrix.macos-vsn}}-OTP-${{steps.configure.outputs.otp_vsn}}.tar.gz
            ${{runner.temp}}/otp/macos64-${{matrix.macos-vsn}}-OTP-${{steps.configure.outputs.otp_vsn}}.sha256.txt
          tag_name: macos64-${{matrix.macos-vsn}}/OTP-${{steps.configure.outputs.otp_vsn}}
          target_commitish: ${{steps.update_releases.outputs.target_commitish}}
